spring.application.name=task-manager
spring.profiles.active=dev

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000