spring.datasource.url=${DB_URL}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

cors.allowed-origins=${FRONTEND_URL}

logging.level.org.springframework=INFO
logging.level.io.github.arkaman=DEBUG

server.port=${PORT:8080}